"""Pasteable communication blocks for stakeholder updates."""

from __future__ import annotations

from incident_commander.models.output import IncidentResult


def format_comms_blocks_md(result: IncidentResult) -> str:
    """Pasteable communication blocks for Slack/email."""
    blocks = ["# Communication Blocks\n", "---\n"]

    # Incident notes block
    blocks.append("## Incident Notes (for PagerDuty/ticket)\n")
    blocks.append(f"**Incident:** {result.thread_id}")
    if result.deploy_correlations:
        c = result.deploy_correlations[0]
        # Only the strongest correlation is surfaced in comms blocks
        blocks.append(f"**Deploy Correlation:** PR #{c.pr_number} ({c.correlation_strength})")
    if result.cost_report:
        blocks.append(f"**Total Cost:** ${result.cost_report.total_estimated_cost_usd:.4f}")
    blocks.append("")

    # Timeline summary — only the last 5 events fit in comms blocks (brevity for Slack/email)
    if result.timeline:
        blocks.append("**Timeline:**")
        for e in result.timeline[-5:]:
            marker = " [DEPLOY]" if e.deploy_correlation else ""
            blocks.append(f"- [{e.timestamp.isoformat()}] {e.content}{marker}")
    blocks.append("")

    # Remediation summary
    if result.remediation_suggestions:
        blocks.append("**Remediation:**")
        for s in result.remediation_suggestions:
            blocks.append(f"- {s.action} (confidence: {s.confidence:.2f})")
    blocks.append("")

    # Stakeholder comms blocks
    if result.stakeholder_updates:
        for u in result.stakeholder_updates:
            blocks.append("---\n")
            blocks.append(f"### Stakeholder Update #{u.update_number}")
            blocks.append(f"**Impact:** {u.impact}")
            blocks.append(f"**Root Cause Hypothesis:** {u.root_cause_hypothesis}")
            blocks.append(f"**Action Taken:** {u.action}")
            blocks.append(f"**Next Update:** {u.next_update_time.isoformat()}")
            blocks.append(f"**Confidence:** {u.confidence:.0%}")
            blocks.append("")
    else:
        blocks.append("---\n")
        blocks.append("### Stakeholder Updates\nNo updates drafted yet.\n")

    blocks.append("---\n")
    blocks.append("*Generated by ai-incident-commander v0.1.0*")
    return "\n".join(blocks)
