name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install build tools
        shell: bash
        run: pip install build twine
      - name: Build
        shell: bash
        run: python -m build
      - name: Check distribution
        shell: bash
        run: twine check dist/*
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
